### ISSUE TITLE
Move to ESM

### ISSUE THREAD

**Issue by dhrubabasu** [ava-labs/avalanchejs#237]
Considering we're targeting at least Node.js 14.16.0, we should consider moving to [Pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

This move should also bring down our [bundle size](https://bundlephobia.com/package/avalanche@3.7.0).

(didn't mean to assign it)

**Comment by cgcardona** [comment]
Can you create a small prototype of this to help me understand what exactly we would need to change?

[This page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) suggests this there is no support in IE for this feature but perhaps that doesn't matter since we're transpiling from ts -> js in our final build.

Does this work w/ ts? I noticed that .mjs files will never be supported in typescript.

Are there any downsides to this decision? Are apps that consume avalanchejs going to be impacted in any way or is this just a syntax and build change on the avalanchejs side?

Thanks for looking into this

**Comment by dhrubabasu** [comment]
We'd need to change our build step, probably to Rollup which is better than Webpack.

Correct, IE does not support ESM out of the box. I'd argue that app developers have their own build step for other dependencies so the onus should be on them to modify their build step to support whichever browsers they want.

This does work with ts, we'll need to look into how to configure Rollup correctly.

The only downside is that people who are dropping in avalanchejs as a global javascript file on a webpage may experience issues with some users. I don't think this is an issue because that isn't behavior we want to support anyway.

**Comment by paOol** [comment]
we may use Electron to build a GUI,
and it looks like ESM is not yet supported.
https://github.com/electron/electron/issues/21457

**Comment by dhrubabasu** [comment]
Seems like there are workarounds for Electron (eg https://github.com/electron/electron/issues/21457#issuecomment-858214526)

**Comment by paOol** [comment]
adding to the roadmap thread and closing this issue.
