### ISSUE TITLE
Package is too big

### ISSUE THREAD

**Issue by collincusce** [ava-labs/avalanchejs#7]
This thing is over 1MB in size once bundled. That's mostly due to the crypto helper libraries we're using. Need to figure out how to make that smaller and keep the functionality.

**Comment by paulmillr** [comment]
Check out my [noble-secp256k1](https://github.com/paulmillr/noble-secp256k1). It's pure typescript/javascript library and it's faster than most other libraries. Wrote a blog post about it: https://paulmillr.com/posts/noble-secp256k1-fast-ecc/.

It works great with node and all major browsers except for Safari. Safari unfortunately doesn't have bigints, but is going to add 'em soon.

Using noble-secp instead of bn.js and current secp lib would allow you to reduce the bundle size by a huge chunk.

**Comment by collincusce** [comment]
Thank you, but this isn't the issue. We use the same elliptic library that Ethereum uses, which is reasonably decomposable and packages well. The problem is the other stuff we want, like chacha poly1305 et al that's is found in the CryptoHelpers sub-library in slopes. The best solution I've seen at this point is to make that a completely separate library package.

**Comment by paulmillr** [comment]
Is there any reason to use chacha instead of aes-gcm? gcm is widely supported and takes about [40 lines of code](https://github.com/paulmillr/micro-aes-gcm) to implement in a cross-platform way. The reason being: it's built-in into node & browsers.

**Comment by collincusce** [comment]
There's a load of reasons to use ChaChaPoly1305 over AES: 

https://crypto.stackexchange.com/questions/34455/whats-the-appeal-of-using-chacha20-instead-of-aes?fbclid=IwAR0Jjaj_vF4y-QWZc2Vjd_NPbloPHWVVYYy1NkCfvKsiecCrzaoZh7GoQX4

We don't let browsers dictate our security standards. The wallet will use ChaChaPoly1305. Gecko actually used to export this EXACT SAME format, but it was removed for a pure binary database dump, for reasons I'm still not clear on. 

Anyway, back to your question: browsers really don't support BigInt either, but we have libraries which work around it. Same with ChaCha.

**Comment by paulmillr** [comment]
Your call obviously, I don't care much here.

I wouldn't call "swiftness & lack of cache timing attacks **but only when AES-NI ain't implemented**" as "load of reasons". AES-gcm is perfectly fine. These issues automatically disappear once AES-NI compatible CPU is used. Timing attacks are very hard to execute. JS / Go are vulnerable to them in any case, since these are the languages with garbage collection. Js has jit. And it's not like you're encrypting terabytes of data.

New tech should not be rushed to. Doing so with djb's (chacha/poly creator) other piece aka ed25519 resulted in terrible vulnerabilities called "torsion point attack". [Other projects](https://www.getmonero.org/2017/05/17/disclosure-of-a-major-bug-in-cryptonote-based-currencies.html) got badly affected by this. A whole new arithmetics [was invented](https://ristretto.group/) to combat this, and now everyone is pushing towards ed25519 with the workaround. Meanwhile folks started heading back to [prime order curves](https://github.com/pornin/curve9767).

**Comment by collincusce** [comment]
I head you. I suggest you should check out chacha a bit more, it's pretty robust and fairly widely used, despite browser adoption.

**Comment by paulmillr** [comment]
I like it, esp for when aes-ni isn’t implemented — encrypting tls traffic on low-end mobile phones is a perfect use case for it.

**Comment by collincusce** [comment]
I'm hearing what you're saying. Now that I've stepped away from coding and had a breather, I can get perspective. Maybe I'm too married to ChaCha, I'll have a think on it. Personally, I prefer it, but if availability is an issue, then maybe making it "official" isn't really the best thing. Especially with small amounts of data. Again, not sold entirely, but I'll have a think on it.

**Comment by paulmillr** [comment]
Soatok recently provided more reasons to ditch GCM: https://soatok.blog/2020/05/13/why-aes-gcm-sucks/

tl;dr in addition to what i've said above:

- using ghash to calculate MAC may create some collisions, so it can't be used in new PAKEs (not our case)
- short nonces: max blob size is 64gb (not our case), max amount of msgs w one nonce: around 2^48 (not our case)

In the end he mentions "Don’t throw AES-GCM out just because of my opinions. It’s very likely the best option you have." 😊

**Comment by collincusce** [comment]
I really do feel like a native JS implementation of ChaCha would work. I mean I know where to snag a really light weight one, but I don't just trust any random crypto implementation I find on the internet, ya feel? 

Like if you view source on this page, there's a very small lightweight version: https://asecuritysite.com/encryption/poly1305

...and if you check NPM you'll find some as well. 

If I'm going to be this picky, though, I should maybe consider wrappers around WebCrypto using AES instead.

I'm really feeling like CryptoHelpers should not be directly included in slopes, though, and should be its own standalone helper library if anything.

**Comment by paulmillr** [comment]
I trust dchest's stuff. See: https://github.com/StableLib/stablelib/tree/master/packages/xchacha20poly1305. He makes great crypto.

Same problem as most others: too many dependencies, but at least it's all his. Perhaps the result would not be too big with it.

**Comment by soatok** [comment]
@paulmillr 

> Soatok recently provided more reasons to ditch GCM: https://soatok.blog/2020/05/13/why-aes-gcm-sucks/

Ohai!

> I trust dchest's stuff. See: https://github.com/StableLib/stablelib/tree/master/packages/xchacha20poly1305. He makes great crypto.

There's also:

* https://www.npmjs.com/package/xchacha20-js
* https://www.npmjs.com/package/poly1305-js

If you're looking for "minimal dependencies". They're used in [sodium-plus](https://www.npmjs.com/package/sodium-plus), but as standalone packages.

**Comment by collincusce** [comment]
Ohhhhhh thanks! @soatok . Hey @cgcardona Can you look into this when you get a chance?

**Comment by cgcardona** [comment]
Confirmed. I'll look in to it.

**Comment by collincusce** [comment]
Latest push on the development branch ditched libsodium and switched chacha20poly1305 to AES-GCM. This reduced us from 1.2mb to ~850kb.

Still more work can be done to reduce file size, but that's a nice start.

**Comment by collincusce** [comment]
The package is where it is for the time being. Optimization can be handled through partial import facilities in nodejs.
