### ISSUE TITLE
Failing to export C-Chain funds on Etna

### ISSUE THREAD

**Issue by containerman17** [ava-labs/avalanchejs#911]
When I run [examples/c-chain/export.ts](https://github.com/ava-labs/avalanchejs/blob/master/examples/c-chain/export.ts) on the Fuji endpoint (`https://api.avax-test.network`), everything works well, and funds are exported as expected. However, when I attempt the same on the Etna devnet (`https://etna.avax-dev.network`), it throws the error: `tx was issued with a different network ID`.

Everything seems correctly set up, with the transaction object showing `networkId: 76` for the Devnet and `networkId: 5` for Fuji, which should be right. The full code with logs is in the gist below:
[https://gist.github.com/containerman17/0eda6e98ea791363655bdd2d8fa79614](https://gist.github.com/containerman17/0eda6e98ea791363655bdd2d8fa79614)

**Comment by containerman17** [comment]
I also tried this on `master` but only with the `https://etna.avax-dev.network` endpoint. The result is the same: `Error: tx was issued with a different network ID`.

**Comment by meeh0w** [comment]
There was a bug that could cause this issue to appear, but it was fixed some time ago (https://github.com/ava-labs/avalanchejs/pull/875/files).

When I run your example code against the Etna devnet, it works (it fails for Fuji, but that's because `getFeeConfig()` fails - different problem that needs fixing).

If you're running your example gist within the AvalancheJS repository, please make sure to build it first (`yarn build`) and comment out the Fuji call.

Let me know if that helps :)

**Comment by containerman17** [comment]
It helped, thanks! Published the master branch here to use in projects https://www.npmjs.com/package/avalanchejs-bleeding-edge
